// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblOrder_addColReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblOrder_addColReason));
        
        string IMigrationMetadata.Id
        {
            get { return "201808200633090_editTblOrder_addColReason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
