// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblCus_addCol_fbID_GoogleID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblCus_addCol_fbID_GoogleID));
        
        string IMigrationMetadata.Id
        {
            get { return "201808250454236_editTblCus_addCol_fbID_GoogleID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
