// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblDiscount_addColDiscountCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblDiscount_addColDiscountCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201808040738142_editTblDiscount_addColDiscountCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
