// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblOrder_addColOrderType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblOrder_addColOrderType));
        
        string IMigrationMetadata.Id
        {
            get { return "201808161039075_editTblOrder_addColOrderType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
