// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblProduct_editColDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblProduct_editColDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201808180506408_editTblProduct_editColDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
