// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editTblImage_addColOffset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTblImage_addColOffset));
        
        string IMigrationMetadata.Id
        {
            get { return "201807250825329_editTblImage_addColOffset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
