// <auto-generated />
namespace CMS_DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editEmp_addColQuote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editEmp_addColQuote));
        
        string IMigrationMetadata.Id
        {
            get { return "201808080334052_editEmp_addColQuote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
